### ISSUE TITLE
Summary- meets expectations

### ISSUE THREAD

**Issue by ghost** [PerezOnline/prj-rev-bwfs-dasmoto#4]
Nice work! You have good alt attributes and indentation. For improvement, you can add more comments to the code. As a further challenge, consider adding another page to your site with a video, text box, and some buttons. Based on your work here, I think you are ready for it!

**Comment by PerezOnline** [comment]
Many thank for reviewing. I will definitely add more comments to the code and work on a page with some more challenges :-)
